#include <iostream>

using namespace std;

 int c = 45; 

int main() {
       string name;

//    ********************Built in data type*************************
//     int a, b, e; 

//     cout << "Enter the value of a:" << endl;
//     cin >> a;

//     cout << "Enter the value of b:" << endl;
//     cin >> b;

//    e = a + b; 

//     cout << "The sum is: " << e << endl;

//     cout << "The global e is: " << e << endl; 

//    ********************Float,long and double Literals*************************

// float d =34.4;
// long double y =34.4;
// cout<<"The size of 34.4 is"<<sizeof(34.4)<<endl;
// cout<<"The size of 34.4f is"<<sizeof(34.4f)<<endl;
// cout<<"The size of 34.4F is"<<sizeof(34.4F)<<endl;
// cout<<"The size of 34.4l is"<<sizeof(34.4l)<<endl;
// cout<<"The size of 34.4L is"<<sizeof(34.4L)<<endl;

// cout<<"The value of d is:"<<d<<endl;
// cout<<"The value of y is:"<<e; 

//    ********************Refrence Variables*************************

float x= 455;
float & z= x;

cout<<x;

}